### PR TITLE
Minor ES6-ish refactorings

### PR DESCRIPTION
**Pull request by rwaldron**
- make use of property shorthands ( {foo: foo} => {foo} )
- Spread is a better apply
- super at the top where possible
- no parens around single args for arrows

Signed-off-by: Rick Waldron waldron.rick@gmail.com

### CODE REVIEW

**Comment by sindresorhus** [comment]
:+1:

**Comment by passy** [comment]
This is great! :+1:

**Comment by rwaldron** [comment]
Rebased to addyosmani/traceur-todomvc@master

**Comment by addyosmani** [comment]
It looks like we currently have just a few little merge conflicts left to resolve but it should be good to merge right after.

Thanks so much for the changes, Rick!

**Comment by passy** [comment]
Merged via 2571676eb66e3495b73a94c7b95270a0b4103013. Thank you!

**Pull request closed without merging**
