### PR TITLE
Dynamic Module Loader Support

### PR DESCRIPTION
**Pull request by guybedford**
Putting this here as a discussion point - I don't expect it to be accepted immediately.

I had to remove the "const" and "let" statements, for a reason I can't work out. I'm not sure if there is a compilation option I am missing here.

Other than that, this demonstrates complete dynamic loading of ES6. I only changed the "module" into its own file. We can potentially reference the external scripts (Backbone etc) as moduleIDs as well. Unfortunately this would have been done with ondemand, which is now in flux, so perhaps we can wait on this.

I completely understand though if you'd prefer this example to use a build-based system rather than this dynamic browser-based workflow. Both are completely valid scenarios.

### CODE REVIEW

**Comment by addyosmani** [comment]
It's great to get a start on this. Thanks Guy! I think we'll need to work out the issues around `let` and `const` having to be dropped before we can accept it, but happy to dive in further into the cause. Can you remember the exceptions you were getting when you tried keeping them in?

**Comment by guybedford** [comment]
Sure, no problem! Erik actually suggested the option that needs to be added to sort this out here - https://github.com/google/traceur-compiler/issues/334#issuecomment-24075465

I can add this in as a default in the module loader, and then also allow easier customization of the Traceur options as well. Should be able to get to this by tomorrow hopefully.

**Comment by guybedford** [comment]
The `const` and `let` statements are now working. In terms of where this goes, as I say up to you what workflow makes sense. I've been discussing with Erik (https://github.com/google/traceur-compiler/issues/334#issuecomment-24084380) to see if we can work around needing to use both Traceur and Esprima, which would make this approach more performant than it currently is.

In terms of how these ideas are shared with users, happy to discuss further / trust your judgement. Could be a separate project, or we can wait until the build workflow is fully working as necessary.

**Comment by addyosmani** [comment]
@guybedford would you be interested in updating your PR to work with the latest version of the ModuleLoader? I would absolutely love to have support for it in this project and it could even serve as a reference example that you could point to from the project readme. Interested?

**Comment by guybedford** [comment]
@addyosmani sure, shouldn't be too tricky at all. Will update the PR in the next few days.

**Comment by guybedford** [comment]
I've pretty much got this working, but am waiting on https://github.com/google/traceur-compiler/issues/595, due to the block binding support not working at the moment. Will post back as soon as we make progress on this.

**Comment by addyosmani** [comment]
Thanks for your work on this!

**Comment by guybedford** [comment]
If you want to speed this along, it may be worth dropping the `const` support for now. Traceur seems to discourage it for performance reasons?

**Comment by addyosmani** [comment]
@guybedford how about we include `const` and the description, but comment it out and mention the reason for not using it by default (the Traceur block binding reasoning). This way we're able to stay on the fast path without the cost of not explaining `const` for those interested.

**Comment by guybedford** [comment]
Ok I've finally added this (was chasing the Traceur issue for a while, but no luck, and I think they have more important things to worry about right now!).

Thanks for your patience - the jspm rewrite for the new ES6 Module Loader has been taking up all my time recently.

I've also released a 0.4.1 of the ES6 Module Loader to go with this which is very nicely stable now.

Anything else just let me know. I can rebase if necessary?

**Comment by addyosmani** [comment]
@guybedford Thanks for trying to chase up the Traceur issue. I know they've had long-term issues with implementing fixes for all but the most critical for features so your efforts there are appreciated.

I can imagine JSPM's rewrite has been keeping you busy. I hope the work on that is going well :) Really glad to hear that we now consider ESML stable.

If you could rebase the PR (LGTM) I'll merge. I'll find a place for us to add back in the `const` explanation as a side-note as developers may still benefit from knowing about it.

Cheers!

**Comment by guybedford** [comment]
Ok I've finally got a decent commit together for this.

@addyosmani thanks for considering this - glad to have stuff moving as I think getting word out is pretty important now.

I've gone with the `System.import` approach instead of the `<script type="module">` because we should really combine this project with a build workflow that involves including a `<script>` that pre-populates the registry. A `<script type="module">` with an `import` needs dynamic parsing as it's ES6 syntax, so wouldn't be compatible with a build.

As for how this build workflow will work, this should be possible as a standard Traceur build that outputs `System.set` or `System.define` calls to create a bundle. Perhaps you can get some advice that side on how we can get this running. I'd be very keen to see the full workflow in action.

But this is at least a start for now.

Yeah, jspm has really sucked up my time! It's looking good though and with some luck all the jspm projects can be updated to the new polyfill, with associated upgrades before the end of this month.

**Comment by addyosmani** [comment]
@guybedford Totally understand :) Thanks so much for working on bringing in these changes. I've been hacking on a build workflow (separately) for projects that an practically use Traceur + ES6 Module Transpiler on production level apps and I'm slowly making progress there. I think the hardest part is factoring in what else Traceur doesn't do which may require additional polyfill libraries (which can of course slow down your load time). It's an interesting set of problems :)

On this PR: it looks like it may still need to be rebased before we can land it. Do you think you'll have time to do this? If so that would be awesome and we'd hugely appreciate it. If not, I can manually bring in the changes and add attribution in the commit message but just wanted to check with you beforehand :)

**Comment by guybedford** [comment]
@addyosmani sure I'm looking into this, but just ran into another bug in the process. Will sort this out.

In terms of a build workflow, if Traceur implement a `System.set` build method (which Erik just mentioned now) that would be the ideal system for this project. I don't think the AMD build workflow would be worth integrating here unfortunately (even though it works), at least not until we have bundling.

**Comment by guybedford** [comment]
Ok this should all be working now. Let me know if there is anything else. I tried to bring all the copy across in a way that makes sense, but it may be worth working on this a little.

Where `let` or `const` statements were removed, I've commented what they were as well so we can potentially change this back in future.

Then as soon as there is even the slightest sign of a build workflow, I'll keep this updated - makes for a good model repo!

**Comment by addyosmani** [comment]
Landed. Once again, thank you so much for working on this. Your continued help in getting this in place has been greatly appreciated. Thanks for adding the additional comments.

**Comment by guybedford** [comment]
@addyosmani great! Any questions at all on the build workflow just let me know.

**Pull request merged**
